### PR TITLE
add ranking to stage ranking query

### LINKED ISSUE #31: Ranking number should be provided when using `StageRanking`.
```
// Query
query {
  stageRanking(limit: 100) {
    ranking
    avatarAddress
    clearedStageId
    name
  }
}

// Data
{
  "data": {
    "stageRanking": [
      {
        "ranking": 1,
        "avatarAddress": "...",
        "clearedStageId": 10000020,
        "name": "..."
      },
      {
        "ranking": 2,
        "avatarAddress": "...",
        "clearedStageId": 10000020,
        "name": "..."
      },
      {
        "ranking": 3,
        "avatarAddress": "...",
        "clearedStageId": 10000019,
        "name": "..."
      },
      {
        "ranking": 4,
        "avatarAddress": "...",
        "clearedStageId": 10000019,
        "name": "..."
      },
...
}
```
Desired query/data is like this.

### PR DESCRIPTION
**Pull request by area363**
Resolves #31.

**Query result with ranking**
image

### CODE REVIEW

**Comment by area363** [comment]
Commit [add avatarAddress parameter](https://github.com/planetarium/NineChronicles.DataProvider/pull/33/commits/85a2f810f6ad2c88c38e1a9efd2aeb42b685f985) resolves #32.

**Comment by area363** [comment]
> Commit [add avatarAddress parameter](https://github.com/planetarium/NineChronicles.DataProvider/pull/33/commits/85a2f810f6ad2c88c38e1a9efd2aeb42b685f985) resolves #32.
> 
> **Query result with avatarAddress argument**
> image

@Unengine Should `clearedStageId` values be unique? To elaborate, if `player A` cleared `stage 5` a hundred times, should I only show one result for that stage? Please let me know your intention for this issue :pray:

**Comment by Unengine** [comment]
> > Commit [add avatarAddress parameter](https://github.com/planetarium/NineChronicles.DataProvider/pull/33/commits/85a2f810f6ad2c88c38e1a9efd2aeb42b685f985) resolves #32.
> > **Query result with avatarAddress argument**
> > image
> 
> @Unengine Should `clearedStageId` values be unique? To elaborate, if `player A` cleared `stage 5` a hundred times, should I only show one result for that stage? Please let me know your intention for this issue 🙏

Yes, it should be unique. Only **one** highest cleared stage id should be shown.

**Comment by area363** [comment]
@Unengine Query has been adjusted!
image

**Review by Unengine — APPROVED** [review]

**Review by longfin — APPROVED** [review]

**Pull request merged**
